# This is a basic workflow to help you get started with Actions

name: Release to Pypi

# Controls when the workflow will run
on:
  push:
    branches: [ "trunk" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ReleaseName: ${GITHUB_REF_NAME}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(github.event.head_commit.message, '@release')
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: stone-home/action-pypi-release@v1.0.0
        with:
          github-token: ${{ secrets.PAT }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}